### ISSUE TITLE
Project is indented using tabs. Spaces would be better.

### ISSUE THREAD

**Issue by hansfbaier** [hydrausb3/hydrausb3_fw#11]
Indentation seems to be by tabs.
Spaces would be better, because then vertical alignment would
be consistent across editors with different tab width settings:
![image](https://user-images.githubusercontent.com/148607/184015722-bbde5e1a-57cf-491f-8722-1496bda29b1c.png)

**Comment by bvernoux** [comment]
It is the intended behavior when using astyle like described in https://github.com/hydrausb3/hydrausb3_fw/blob/main/CODING_STYLE.md
So we shall apply that coding rules even if things like that are not perfect the good point is it is done automatically by astyle

**Comment by hansfbaier** [comment]
Ah, ok. Thanks.
