### ISSUE TITLE
The SDK in SRC should be a git submodule

### ISSUE THREAD

**Issue by hansfbaier** [hydrausb3/hydrausb3_fw#15]
**Is your feature request related to a problem? Please describe.**
If I want to start my own project based on the SDK, I have to pull in the examples,
which I don't want.

**Describe the solution you'd like**
make SRC a git submodule, so everyone can just integrate the SDK as such.

**Describe alternatives you've considered**
An alternative could be a fork of hydraUSB and then delete the example,
but that would create lots of unrelated forks of the project.

**Comment by bvernoux** [comment]
https://github.com/hydrausb3/wch-ch56x-bsp created

**Comment by bvernoux** [comment]
Implemented in commit https://github.com/hydrausb3/hydrausb3_fw/commit/f9f79d0fe051ecd6c51acf05f79861a0a64276f5
