### ISSUE TITLE
Firmware for libsigrok compatibility

### ISSUE THREAD

**Issue by abraxa** [hydrausb3/hydrausb3_fw#21]
Hi Benjamin,

Someone created this PR for libsigrok: https://github.com/sigrokproject/libsigrok/pull/239

Do you happen to know anything about it? I wonder if someone wrote a firmware for the WCH-CH569 that emulates the fx2lafw protocol and I figured you'd be the most likely person to know since the PR author isn't responding.

Either way, do you know of someone writing a firmware that produces a logic analyzer functionality? Might be worth writing a compatible driver for libsigrok if so.

**Comment by bvernoux** [comment]
Unfortunately I'm not aware of that PR and I do not have any contact with the author of that PR.
I'm not aware of anyone writing a firmware to do logic analyzer functionality for WCH CH569 to be clear there was pratically no any feedback / PR for hydrausb3_fw (except the amazing work done by https://github.com/kauwua on the [lib](https://github.com/hydrausb3/wch-ch56x-lib) and [hydradancer_fw](https://github.com/HydraDancer/hydradancer_fw)... )

**Comment by abraxa** [comment]
Thanks for your feedback, unfortunately I have no option but to cancel the PR then. I do really wonder how much work it would be to create a firmware with this functionality and whether we'd have the same issues here as we have with the FX3. The biggest problem was the renumeration where the FX3 showed up on a different USB bus with a whole different VID/PID after the firmware was uploaded in USB2 mode. This issue would be the same here, right?

**Comment by bvernoux** [comment]
> Thanks for your feedback, unfortunately I have no option but to cancel the PR then. I do really wonder how much work it would be to create a firmware with this functionality and whether we'd have the same issues here as we have with the FX3. The biggest problem was the renumeration where the FX3 showed up on a different USB bus with a whole different VID/PID after the firmware was uploaded in USB2 mode. This issue would be the same here, right?

I'm not aware of that issue with FX3 as I have mainly worked on WCH CH569 which probably will do not have such limitation especially as [kauwua](https://github.com/kauwua) has wrote a full low level USB2 / USB3 stack https://github.com/hydrausb3/wch-ch56x-lib maybe to be cross checked with [kauwua](https://github.com/kauwua)
The main issue anyway to do a good Logic Analyzer with WCH C569 is there is no DMA on GPIO so it will be pretty slow to read the GPIO with the CPU fast enough to have something like > 10MSPS 
The only other way to sample the GPIO quickly (up to 120MHz in fact linked to MCU speed) will be to use HSPI but it have mandatory framing with header... so not usable for LA ...

**Comment by abraxa** [comment]
Thanks, that is important to know and a bummer indeed. With DMA for the I/O, this could've been a serious FX3 competitor.
