### ISSUE TITLE
Serial debug not working in blinky example

### ISSUE THREAD

**Issue by hansfbaier** [hydrausb3/hydrausb3_fw#5]
The serial console is not initialized/working in the blinky example.
This is very important, because the blinky is the baseline project
for most projects one might start.
Would be great if it also printed "Blink!" on the serial console.

**Comment by bvernoux** [comment]
Yes it can be improved like in your proposal
Note: I plan a refactor of log_xxx API too see https://github.com/hydrausb3/hydrausb3_fw/issues/4

In future I want to push more towards SerDes for traces which is unique feature to avoid slow UART
So it can be added with UART today(especially in HydraUSB3_Blink_ULED example) and write other examples with traces over USB3, SerDes or even HSPI

**Comment by bvernoux** [comment]
PR is welcome (like that you can do like you wish thanks to keep it simple)

**Comment by bvernoux** [comment]
Fixed in commit https://github.com/hydrausb3/hydrausb3_fw/commit/efb70146722aece07f14af2266381314ba90f7cc any feedback is welcome
